services:
  postgres:
    image: postgres:16

    container_name: genesis-postgres

    restart: unless-stopped

    environment:
      POSTGRES_USER: genesis
      POSTGRES_PASSWORD: genesis123
      POSTGRES_DB: genesis

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7

    container_name: genesis-redis

    restart: unless-stopped

    ports:
      - "6379:6379"

volumes:
  postgres_data: