"""add_provider_name_to_jobs

Revision ID: 715546ed8b6f
Revises: 9361c11319f6
Create Date: 2026-06-27 14:00:07.080307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '715546ed8b6f'
down_revision: Union[str, Sequence[str], None] = '9361c11319f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('provider_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'provider_name')
    # ### end Alembic commands ###
